/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab_8;
import java.awt.Color;
import java.awt.Graphics;
/**
 *
 * @author User
 */
public class Zadanie_1 extends javax.swing.JFrame {

    /**
     * Creates new form Zadanie_1
     */
    public Zadanie_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zadanie_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zadanie_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zadanie_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zadanie_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Zadanie_1().setVisible(true);
            }
        });
    }
    public void paint(final Graphics g) {
        g.drawLine(10, 35, 500, 35);
        g.drawLine(10, 35, 10, 500);
        g.drawLine(500, 35, 500, 500);
        g.drawLine(500, 500, 10, 500);
        final Color oldColor = g.getColor();
        Color newColor = new Color(0, 0, 255);
        newColor = new Color(0, 0, 0);
        g.setColor(newColor);
        g.drawLine(150, 480, 350, 480);
        g.drawLine(150, 480, 150, 250);
        g.drawLine(350, 480, 350, 250);
        g.setColor(newColor);
        g.drawLine(150, 250, 350, 250);
        g.drawLine(150, 250, 250, 200);
        g.drawLine(350, 250, 250, 200);
        g.setColor(newColor);
        g.drawLine(200, 480, 200, 350);
        g.drawLine(200, 350, 300, 350);
        g.drawLine(300, 350, 300, 480);
        g.drawLine(290, 420, 290, 430);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

